/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLengkapiProfilRouteImport } from './routes/_authenticated/lengkapi-profil'
import { Route as AuthenticatedEditorBukuRouteImport } from './routes/_authenticated/editor-buku'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'

const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLengkapiProfilRoute =
  AuthenticatedLengkapiProfilRouteImport.update({
    id: '/lengkapi-profil',
    path: '/lengkapi-profil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditorBukuRoute = AuthenticatedEditorBukuRouteImport.update({
  id: '/editor-buku',
  path: '/editor-buku',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/katalog': typeof KatalogRoute
  '/app': typeof AuthenticatedAppRoute
  '/editor-buku': typeof AuthenticatedEditorBukuRoute
  '/lengkapi-profil': typeof AuthenticatedLengkapiProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/katalog': typeof KatalogRoute
  '/app': typeof AuthenticatedAppRoute
  '/editor-buku': typeof AuthenticatedEditorBukuRoute
  '/lengkapi-profil': typeof AuthenticatedLengkapiProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/katalog': typeof KatalogRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/editor-buku': typeof AuthenticatedEditorBukuRoute
  '/_authenticated/lengkapi-profil': typeof AuthenticatedLengkapiProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/katalog'
    | '/app'
    | '/editor-buku'
    | '/lengkapi-profil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/katalog' | '/app' | '/editor-buku' | '/lengkapi-profil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/katalog'
    | '/_authenticated/app'
    | '/_authenticated/editor-buku'
    | '/_authenticated/lengkapi-profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KatalogRoute: typeof KatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lengkapi-profil': {
      id: '/_authenticated/lengkapi-profil'
      path: '/lengkapi-profil'
      fullPath: '/lengkapi-profil'
      preLoaderRoute: typeof AuthenticatedLengkapiProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editor-buku': {
      id: '/_authenticated/editor-buku'
      path: '/editor-buku'
      fullPath: '/editor-buku'
      preLoaderRoute: typeof AuthenticatedEditorBukuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedEditorBukuRoute: typeof AuthenticatedEditorBukuRoute
  AuthenticatedLengkapiProfilRoute: typeof AuthenticatedLengkapiProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedEditorBukuRoute: AuthenticatedEditorBukuRoute,
  AuthenticatedLengkapiProfilRoute: AuthenticatedLengkapiProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KatalogRoute: KatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
