/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedLengkapiProfilRouteImport } from './routes/_authenticated/lengkapi-profil'
import { Route as BlogManfaatSistemPerpustakaanDigitalRouteImport } from './routes/blog.manfaat-sistem-perpustakaan-digital'
import { Route as ApiPublicTmpRotateRouteImport } from './routes/api/public/tmp-rotate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLengkapiProfilRoute =
  AuthenticatedLengkapiProfilRouteImport.update({
    id: '/lengkapi-profil',
    path: '/lengkapi-profil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BlogManfaatSistemPerpustakaanDigitalRoute =
  BlogManfaatSistemPerpustakaanDigitalRouteImport.update({
    id: '/blog/manfaat-sistem-perpustakaan-digital',
    path: '/blog/manfaat-sistem-perpustakaan-digital',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTmpRotateRoute = ApiPublicTmpRotateRouteImport.update({
  id: '/api/public/tmp-rotate',
  path: '/api/public/tmp-rotate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/katalog': typeof KatalogRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/lengkapi-profil': typeof AuthenticatedLengkapiProfilRoute
  '/blog/manfaat-sistem-perpustakaan-digital': typeof BlogManfaatSistemPerpustakaanDigitalRoute
  '/api/public/tmp-rotate': typeof ApiPublicTmpRotateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/katalog': typeof KatalogRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/lengkapi-profil': typeof AuthenticatedLengkapiProfilRoute
  '/blog/manfaat-sistem-perpustakaan-digital': typeof BlogManfaatSistemPerpustakaanDigitalRoute
  '/api/public/tmp-rotate': typeof ApiPublicTmpRotateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/katalog': typeof KatalogRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/lengkapi-profil': typeof AuthenticatedLengkapiProfilRoute
  '/blog/manfaat-sistem-perpustakaan-digital': typeof BlogManfaatSistemPerpustakaanDigitalRoute
  '/api/public/tmp-rotate': typeof ApiPublicTmpRotateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/katalog'
    | '/sitemap.xml'
    | '/app'
    | '/lengkapi-profil'
    | '/blog/manfaat-sistem-perpustakaan-digital'
    | '/api/public/tmp-rotate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/katalog'
    | '/sitemap.xml'
    | '/app'
    | '/lengkapi-profil'
    | '/blog/manfaat-sistem-perpustakaan-digital'
    | '/api/public/tmp-rotate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/katalog'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/lengkapi-profil'
    | '/blog/manfaat-sistem-perpustakaan-digital'
    | '/api/public/tmp-rotate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KatalogRoute: typeof KatalogRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogManfaatSistemPerpustakaanDigitalRoute: typeof BlogManfaatSistemPerpustakaanDigitalRoute
  ApiPublicTmpRotateRoute: typeof ApiPublicTmpRotateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lengkapi-profil': {
      id: '/_authenticated/lengkapi-profil'
      path: '/lengkapi-profil'
      fullPath: '/lengkapi-profil'
      preLoaderRoute: typeof AuthenticatedLengkapiProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/manfaat-sistem-perpustakaan-digital': {
      id: '/blog/manfaat-sistem-perpustakaan-digital'
      path: '/blog/manfaat-sistem-perpustakaan-digital'
      fullPath: '/blog/manfaat-sistem-perpustakaan-digital'
      preLoaderRoute: typeof BlogManfaatSistemPerpustakaanDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmp-rotate': {
      id: '/api/public/tmp-rotate'
      path: '/api/public/tmp-rotate'
      fullPath: '/api/public/tmp-rotate'
      preLoaderRoute: typeof ApiPublicTmpRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedLengkapiProfilRoute: typeof AuthenticatedLengkapiProfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedLengkapiProfilRoute: AuthenticatedLengkapiProfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KatalogRoute: KatalogRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogManfaatSistemPerpustakaanDigitalRoute:
    BlogManfaatSistemPerpustakaanDigitalRoute,
  ApiPublicTmpRotateRoute: ApiPublicTmpRotateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
